"use client";

import { useEffect, useState } from "react";
import { adminService } from "@/services/admin.service";
import { IItinerary } from "@/types";
import { 
  Loader2, 
  FileText, 
  Search, 
  MapPin, 
  User, 
  DollarSign, 
  ArrowRight,
  Sparkles
} from "lucide-react";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";

export default function AdminItinerariesPage() {
  const [itineraries, setItineraries] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    const fetchItineraries = async () => {
      try {
        const response = await adminService.getAllItineraries();
        setItineraries(response.data || []);
      } catch (error) {
        console.error("Failed to fetch itineraries:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchItineraries();
  }, []);

  const filteredItineraries = itineraries.filter(it => 
    it.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    it.user?.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    it.destination?.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-10">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="space-y-2">
          <h1 className="text-4xl font-black tracking-tight text-slate-900">Platform Itineraries</h1>
          <p className="text-lg text-slate-500 font-medium">Global oversight of all travel plans generated by Wandr AI.</p>
        </div>
      </div>

      <div className="relative max-w-md">
        <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
        <Input 
          placeholder="Search by title, creator, or destination..." 
          className="pl-11 rounded-2xl border-slate-200 h-12 focus-visible:ring-primary/20"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
        />
      </div>

      {isLoading ? (
        <div className="flex justify-center items-center py-20">
          <Loader2 className="h-10 w-10 animate-spin text-primary" />
        </div>
      ) : filteredItineraries.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {filteredItineraries.map((itinerary) => (
            <Link key={itinerary.id} href={`/itineraries/${itinerary.id}`}>
              <Card className="border-none shadow-lg shadow-slate-200/50 hover:shadow-xl transition-all duration-300 rounded-[2.5rem] overflow-hidden group bg-white">
                <CardContent className="p-8 space-y-6">
                  <div className="flex items-center justify-between">
                    <div className="p-3 bg-primary/10 rounded-2xl text-primary group-hover:bg-primary group-hover:text-white transition-colors">
                      <Sparkles className="h-6 w-6" />
                    </div>
                    <Badge variant="outline" className="rounded-full border-slate-200 text-slate-400 font-medium">
                      {new Date(itinerary.createdAt).toLocaleDateString()}
                    </Badge>
                  </div>

                  <div className="space-y-1">
                    <h3 className="text-2xl font-black text-slate-900 group-hover:text-primary transition-colors line-clamp-1">
                      {itinerary.title}
                    </h3>
                    <div className="flex items-center gap-2 text-sm text-slate-500 font-medium">
                      <User className="h-3.5 w-3.5 text-slate-400" />
                      Created by <span className="text-slate-900 font-bold">{itinerary.user?.name}</span>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4 pt-2">
                    <div className="flex items-center text-sm font-bold text-slate-600 bg-slate-50 p-3 rounded-xl border border-slate-100">
                      <MapPin className="h-4 w-4 mr-2 text-primary/60" />
                      {itinerary.destination?.name}
                    </div>
                    <div className="flex items-center text-sm font-bold text-slate-600 bg-slate-50 p-3 rounded-xl border border-slate-100">
                      <DollarSign className="h-4 w-4 mr-2 text-emerald-500" />
                      Est. ${itinerary.budgetEstimate}
                    </div>
                  </div>

                  <div className="pt-4 flex items-center text-primary font-bold text-sm group-hover:translate-x-2 transition-transform">
                    Review Plan Details <ArrowRight className="h-4 w-4 ml-2" />
                  </div>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      ) : (
        <div className="text-center py-20 bg-slate-50 rounded-[2.5rem] border-2 border-dashed border-slate-200">
          <div className="w-16 h-16 rounded-2xl bg-slate-100 flex items-center justify-center mx-auto text-slate-400 mb-4">
            <FileText className="w-8 h-8" />
          </div>
          <h3 className="text-xl font-bold text-slate-700">No itineraries found</h3>
          <p className="text-slate-500">Global travel plan database is empty or filtered.</p>
        </div>
      )}
    </div>
  );
}
