"use client";

import { useEffect, useState } from "react";
import {
  Users,
  Sparkles,
  TrendingUp,
  ArrowUpRight,
  ArrowDownRight,
  Loader2,
  Calendar,
  Globe
} from "lucide-react";
import { adminService } from "@/services/admin.service";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

interface DashboardStats {
  users: {
    normal: number;
    contentManagers: number;
    total: number;
  };
  platform: {
    destinations: number;
    itineraries: number;
    reviews: number;
  };
  recentUsers?: any[];
}

export function AdminDashboardView() {
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const response = await adminService.getStats();
        setStats(response.data);
      } catch (error) {
        console.error("Failed to fetch dashboard stats:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchStats();
  }, []);

  if (isLoading) {
    return (
      <div className="flex justify-center items-center py-20">
        <Loader2 className="h-10 w-10 animate-spin text-primary" />
      </div>
    );
  }

  const statCards = [
    {
      title: "Total Explorers",
      value: stats?.users.normal || 0,
      icon: Users,
      color: "bg-blue-500",
      description: "Registered travelers",
      trend: "+12.5%",
      trendUp: true
    },
    {
      title: "Destinations",
      value: stats?.platform.destinations || 0,
      icon: Globe,
      color: "bg-emerald-500",
      description: "Locations in database",
      trend: "+4 new",
      trendUp: true
    },
    {
      title: "AI Itineraries",
      value: stats?.platform.itineraries || 0,
      icon: Sparkles,
      color: "bg-purple-500",
      description: "Generated by concierge",
      trend: "+28%",
      trendUp: true
    },
    {
      title: "Content Squad",
      value: stats?.users.contentManagers || 0,
      icon: TrendingUp,
      color: "bg-amber-500",
      description: "Active curators",
      trend: "Steady",
      trendUp: true
    },
  ];

  return (
    <div className="space-y-10">
      {/* Welcome Section */}
      <div className="flex flex-col gap-2">
        <h1 className="text-4xl font-black tracking-tight text-slate-900">Platform Overview</h1>
        <p className="text-lg text-slate-500 font-medium">Here's what's happening on Wandr today.</p>
      </div>

      {/* Stat Grid */}
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
        {statCards.map((card, idx) => (
          <Card key={idx} className="border-none shadow-xl shadow-slate-200/50 rounded-[2rem] overflow-hidden group hover:scale-[1.02] transition-transform duration-300">
            <CardContent className="p-8">
              <div className="flex items-center justify-between mb-6">
                <div className={cn("p-4 rounded-2xl text-white shadow-lg", card.color)}>
                  <card.icon className="h-6 w-6" />
                </div>
                <div className={cn(
                  "flex items-center gap-1 text-xs font-black px-3 py-1.5 rounded-full uppercase tracking-widest",
                  card.trendUp ? "bg-emerald-50 text-emerald-600 border border-emerald-100" : "bg-red-50 text-red-600 border border-red-100"
                )}>
                  {card.trendUp ? <ArrowUpRight className="h-3 w-3" /> : <ArrowDownRight className="h-3 w-3" />}
                  {card.trend}
                </div>
              </div>
              <div className="space-y-1">
                <p className="text-sm font-bold text-slate-500 uppercase tracking-widest">{card.title}</p>
                <p className="text-4xl font-black text-slate-900">{card.value}</p>
              </div>
              <p className="mt-4 text-xs font-medium text-slate-400">{card.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Recent Activity Section */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mt-10">
        <Card className="lg:col-span-2 border-none shadow-xl shadow-slate-200/50 rounded-[2rem] p-8">
          <div className="flex items-center justify-between mb-8">
            <h3 className="text-xl font-black text-slate-900">Recent Explorers</h3>
            <button className="text-sm font-bold text-primary hover:underline">View all</button>
          </div>
          <div className="space-y-6">
            {(stats?.recentUsers || []).length > 0 ? stats?.recentUsers?.map((user: any) => (
              <div key={user.id} className="flex items-center justify-between p-4 rounded-2xl bg-slate-50 border border-slate-100 hover:border-primary/20 transition-colors group">
                <div className="flex items-center gap-4">
                  <div className="h-12 w-12 rounded-full bg-white flex items-center justify-center text-primary font-black shadow-sm border border-slate-100 group-hover:bg-primary group-hover:text-white transition-colors">
                    {user.name.charAt(0).toUpperCase()}
                  </div>
                  <div>
                    <p className="font-bold text-slate-900">{user.name}</p>
                    <p className="text-sm text-slate-500">{user.email}</p>
                  </div>
                </div>
                <Badge variant="outline" className="rounded-full border-slate-200 text-slate-500">
                  {new Date(user.createdAt).toLocaleDateString()}
                </Badge>
              </div>
            )) : (
              <div className="text-center py-10 space-y-4">
                <div className="w-16 h-16 rounded-2xl bg-slate-100 flex items-center justify-center mx-auto text-slate-400">
                  <Users className="w-8 h-8" />
                </div>
                <p className="text-slate-500 font-medium">No recent sign-ups found.</p>
              </div>
            )}
          </div>
        </Card>

        <Card className="border-none shadow-xl shadow-slate-200/50 rounded-[2rem] p-8 bg-slate-900 text-white">
          <h3 className="text-xl font-black mb-8 flex items-center gap-2">
            <Calendar className="h-5 w-5 text-primary" />
            System Events
          </h3>
          <div className="space-y-8">
            <div className="relative pl-6 border-l-2 border-white/10 space-y-1">
              <div className="absolute -left-1.5 top-0.5 h-3 w-3 rounded-full bg-primary" />
              <p className="text-sm font-bold text-white">Weekly Backup Completed</p>
              <p className="text-xs text-white/50">2 hours ago</p>
            </div>
            <div className="relative pl-6 border-l-2 border-white/10 space-y-1">
              <div className="absolute -left-1.5 top-0.5 h-3 w-3 rounded-full bg-emerald-500" />
              <p className="text-sm font-bold text-white">Prisma Client Synchronized</p>
              <p className="text-xs text-white/50">5 hours ago</p>
            </div>
            <div className="relative pl-6 border-l-2 border-white/10 space-y-1">
              <div className="absolute -left-1.5 top-0.5 h-3 w-3 rounded-full bg-blue-500" />
              <p className="text-sm font-bold text-white">Gemini API Connection Stable</p>
              <p className="text-xs text-white/50">8 hours ago</p>
            </div>
          </div>
          <button className="mt-12 w-full rounded-2xl bg-white/10 py-4 text-sm font-bold text-white hover:bg-white/20 transition-colors">
            Check Logs
          </button>
        </Card>
      </div>
    </div>
  );
}
