"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { Calendar, MapPin, DollarSign, Clock, ArrowRight, Loader2, Sparkles, Plus } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { IDestination } from "@/types/destination";

interface IItinerarySummary {
  id: string;
  title: string;
  totalDays: number;
  budgetEstimate: number;
  travelStyle: string;
  createdAt: string;
  destination: IDestination;
}

export function ItineraryList() {
  const [itineraries, setItineraries] = useState<IItinerarySummary[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchItineraries = async () => {
      try {
        setIsLoading(true);
        const response = await api.get<{ data: IItinerarySummary[] }>("/itineraries/my-itineraries");
        setItineraries(response.data || []);
      } catch (error) {
        console.error("Failed to fetch itineraries:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchItineraries();
  }, []);

  if (isLoading) {
    return (
      <div className="flex justify-center items-center py-20">
        <Loader2 className="w-10 h-10 animate-spin text-primary" />
      </div>
    );
  }

  if (itineraries.length === 0) {
    return (
      <div className="text-center py-20 bg-slate-50 rounded-[2.5rem] border-2 border-dashed border-slate-200">
        <div className="w-20 h-20 bg-primary/10 rounded-3xl flex items-center justify-center mx-auto mb-6 text-primary">
          <Plus className="w-10 h-10" />
        </div>
        <h2 className="text-3xl font-black text-slate-800 mb-4">No Itineraries Yet</h2>
        <p className="text-slate-500 max-w-md mx-auto mb-8 text-lg font-medium">
          You haven't generated any travel plans yet. Let our AI help you plan your next adventure!
        </p>
        <Link href="/itineraries/create">
          <Button className="rounded-full px-10 h-14 font-bold text-lg shadow-xl hover:scale-105 transition-transform">
            Create New Itinerary
          </Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="space-y-10">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="space-y-2">
          <h1 className="text-4xl md:text-5xl font-black tracking-tight text-slate-900">
            My Itineraries
          </h1>
          <p className="text-lg text-slate-500 max-w-2xl font-medium">
            Manage and view your personalized travel plans generated by our AI concierge.
          </p>
        </div>
        <Link href="/itineraries/create">
          <Button className="rounded-full px-8 h-12 font-bold shadow-lg hover:shadow-xl transition-all flex items-center gap-2">
            <Plus className="w-5 h-5" />
            New Trip
          </Button>
        </Link>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
        {itineraries.map((itinerary) => (
          <Link key={itinerary.id} href={`/itineraries/${itinerary.id}`}>
            <Card className="border-none shadow-lg shadow-slate-200/50 hover:shadow-xl transition-all duration-300 rounded-[2.5rem] overflow-hidden group bg-white">
              <CardContent className="p-0">
                <div className="flex flex-col sm:flex-row h-full">
                  <div className="relative w-full sm:w-48 h-48 sm:h-auto overflow-hidden shrink-0">
                    <img 
                      src={itinerary.destination.coverImage} 
                      alt={itinerary.title}
                      className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
                    />
                    <div className="absolute inset-0 bg-black/10 group-hover:bg-transparent transition-colors" />
                  </div>
                  
                  <div className="p-8 flex flex-col justify-between flex-grow">
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <Badge className="bg-primary/10 text-primary border-none px-3 py-1 rounded-full font-bold text-xs uppercase tracking-wider">
                          {itinerary.travelStyle}
                        </Badge>
                        <span className="text-xs text-slate-400 font-medium">
                          {new Date(itinerary.createdAt).toLocaleDateString()}
                        </span>
                      </div>
                      
                      <h3 className="text-2xl font-bold text-slate-800 group-hover:text-primary transition-colors line-clamp-1">
                        {itinerary.title}
                      </h3>
                      
                      <div className="grid grid-cols-2 gap-4">
                        <div className="flex items-center text-slate-500 font-medium text-sm">
                          <Clock className="w-4 h-4 mr-2 text-primary/60" />
                          {itinerary.totalDays} Days
                        </div>
                        <div className="flex items-center text-slate-500 font-medium text-sm">
                          <DollarSign className="w-4 h-4 mr-2 text-primary/60" />
                          ${itinerary.budgetEstimate}
                        </div>
                      </div>
                      
                      <div className="flex items-center text-slate-500 font-medium text-sm">
                        <MapPin className="w-4 h-4 mr-2 text-primary/60" />
                        {itinerary.destination.name}, {itinerary.destination.country}
                      </div>
                    </div>
                    
                    <div className="mt-8 flex items-center text-primary font-bold text-sm group-hover:translate-x-2 transition-transform">
                      View Full Plan <ArrowRight className="w-4 h-4 ml-2" />
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>
    </div>
  );
}
